package com.redhat.demos.dm.loan.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Amount")
	private int amount;
	@org.kie.api.definition.type.Label(value = "Duration")
	private int duration;
	@org.kie.api.definition.type.Label(value = "Interest Rate")
	private double interestRate;
	@org.kie.api.definition.type.Label(value = "Approved")
	private boolean approved;
	@org.kie.api.definition.type.Label(value = "Reason")
	private String reason;	

	@org.kie.api.definition.type.Label(value = "message")
	private String message;
	@org.kie.api.definition.type.Label(value = "status")
		private int status;
	@org.kie.api.definition.type.Label(value = "gufi")
		private String gufi;

		public static final int VALIDATE = 1;

		public String getMessage() {
			return this.message;
		}

		public void setMessage(String message) {
			this.message = message;
		}

		public String getGufi() {
			return this.gufi;
		}

		public void setGufi(String gufi) {
			this.gufi = gufi;
		}

		
		public int getStatus() {
			return this.status;
		}

		public void setStatus(int status) {
			this.status = status;
		}

	
	public Message() {
	}

	

	@Override
	public String toString() {
		return String.format("Loan [amount=%s, duration=%s, interestRate=%s, approved=%s, reason=%s]", amount, duration,
				interestRate, approved, reason);
	}

}